return {
  {
    'nvim-treesitter/nvim-treesitter',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        'awk',
        'bash',
        'c',
        'cmake',
        'comment',
        'cpp',
        'css',
        'diff',
        'dockerfile',
        'eex',
        'elixir',
        'erlang',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitignore',
        'go',
        'gomod',
        'gosum',
        'gowork',
        'heex',
        'html',
        'javascript',
        'json',
        'jq',
        'lua',
        'luadoc',
        'make',
        'markdown',
        'ninja',
        'objc',
        'proto',
        'python',
        'regex',
        'rust',
        'sql',
        'terraform',
        'toml',
        'typescript',
        'vim',
        'vimdoc',
        'yaml',
      },
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "e",
          node_incremental = "e",
          node_decremental = "E",
        },
      },
    },
    build = ':TSUpdate',
    dependencies = {
      'nvim-treesitter/nvim-treesitter-textobjects',
    },
  },
}
