add_newline = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[aws]
symbol = "  "
format = 'on [$symbol($profile )(\($region\) )]($style)'

[elixir]
symbol = " "

[docker_context]
disabled = true

[nodejs]
symbol = " "
